# Copyright 2021 Chaos Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- $webhookName := printf "%s.%s.svc" (include "chaos-mesh.svc" .) .Release.Namespace }}
{{- $ca := genCA "chaos-mesh-ca" 1825 }}
{{- $webhookServerCert := genSignedCert $webhookName nil (list $webhookName) 1825 $ca }}
{{- $certManagerEnabled := .Values.webhook.certManager.enabled }}
{{- $timeoutSeconds := .Values.webhook.timeoutSeconds }}
{{- $crtPEM := .Values.webhook.crtPEM }}
{{- $keyPEM := .Values.webhook.keyPEM }}

{{- $webhookApiVersion := "v1beta1" }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
  {{- $webhookApiVersion = "v1" }}
{{- end }}


{{- $supportTimeoutSeconds := false }}
{{- if ge .Capabilities.KubeVersion.Minor "14" }}
{{- $supportTimeoutSeconds = true }}
{{- end }}

{{- if not $certManagerEnabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chaos-mesh.webhook.certs" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-secret
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ ternary (b64enc $webhookServerCert.Cert) (b64enc (trim $crtPEM)) (empty $crtPEM) }}
  tls.key: {{ ternary (b64enc $webhookServerCert.Key) (b64enc (trim $keyPEM)) (empty $keyPEM) }}

{{- if .Values.dashboard.securityMode }}
---
{{- $chaosDaemonCert := genSignedCert "chaos-daemon.chaos-mesh.org" nil (list "localhost" "chaos-daemon.chaos-mesh.org") 1825 $ca }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chaos-mesh.daemon.certs" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: chaos-daemon-cert
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $chaosDaemonCert.Cert }}
  tls.key: {{ b64enc $chaosDaemonCert.Key }}
---
{{- $chaosDaemonClientCert := genSignedCert "controller-manager.chaos-mesh.org" nil (list "localhost" "controller-manager.chaos-mesh.org") 1825 $ca }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chaos-mesh.daemon-client.certs" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: chaos-daemon-client-cert
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $chaosDaemonClientCert.Cert }}
  tls.key: {{ b64enc $chaosDaemonClientCert.Key }}
{{- end }}

{{- end }}

{{- if .Values.controllerManager.chaosdSecurityMode }}
---
{{- $chaosdCA := genCA "chaosd-ca" 1825 }}
{{- $chaosdClientCert := genSignedCert "controller-manager.chaos-mesh.org" nil (list "localhost" "controller-manager.chaos-mesh.org") 1825 $chaosdCA }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "chaos-mesh.chaosd-client.certs" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: chaosd-client-cert
type: Opaque
data:
  ca.crt: {{ b64enc $chaosdCA.Cert }}
  ca.key: {{ b64enc $chaosdCA.Key }}
  tls.crt: {{ b64enc $chaosdClientCert.Cert }}
  tls.key: {{ b64enc $chaosdClientCert.Key }}
{{- end }}
---
{{- if eq $webhookApiVersion "v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else -}}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "chaos-mesh.mutation" . }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  {{- if $certManagerEnabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" .Release.Namespace "chaos-mesh-cert" | quote }}
  {{- end }}
webhooks:
  - name: {{ template "chaos-mesh.webhook" . }}
    {{- if $supportTimeoutSeconds }}
    timeoutSeconds: {{ $timeoutSeconds }}
    {{- if eq $webhookApiVersion "v1" }}
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    {{- end }}
    {{- end }}
    clientConfig:
      {{- if $certManagerEnabled }}
      caBundle: Cg==
      {{- else }}
      caBundle: {{ ternary (b64enc $ca.Cert) (b64enc (trim $crtPEM)) (empty $crtPEM) }}
      {{- end }}
      service:
        name: {{ template "chaos-mesh.svc" . }}
        namespace: {{ .Release.Namespace | quote }}
        path: "/inject-v1-pod"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    failurePolicy: {{ .Values.webhook.FailurePolicy }}
  {{- range $crd := .Values.webhook.CRDS }}
  - clientConfig:
      {{- if $certManagerEnabled }}
      caBundle: Cg==
      {{- else }}
      caBundle: {{ ternary (b64enc $ca.Cert) (b64enc (trim $crtPEM)) (empty $crtPEM) }}
      {{- end }}
      service:
        name: {{ template "chaos-mesh.svc" $ }}
        namespace: {{ $.Release.Namespace | quote }}
        path: /mutate-chaos-mesh-org-v1alpha1-{{ $crd }}
    failurePolicy: Fail
    name: m{{ $crd }}.kb.io
    {{- if $supportTimeoutSeconds }}
    timeoutSeconds: {{ $timeoutSeconds }}
    {{- if eq $webhookApiVersion "v1" }}
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    {{- end }}
    {{- end }}
    rules:
      - apiGroups:
          - chaos-mesh.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          {{- if eq $crd "schedule" }}
          - schedules
          {{- else if eq $crd "workflow" }}
          - workflows
          {{- else if eq $crd "physicalmachine" }}
          - physicalmachines
          {{- else if eq $crd "statuscheck" }}
          - statuschecks
          {{- else }}
          - {{ $crd }}
          {{- end }}
  {{- end }}
---
