name: E2E test matrix

on:
  push: {}
  pull_request:
    branches:
      - master
      - release-*

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout codes
      uses: actions/checkout@v2
    - name: build e2e images
      run: |
        make image e2e-image
    - name: save docker images
      run: |
        mkdir -p ./output/saved-images
        docker image save localhost:5000/chaos-mesh/chaos-dashboard:latest > ./output/saved-images/chaos-dashboard.tgz
        docker image save localhost:5000/chaos-mesh/chaos-daemon:latest > ./output/saved-images/chaos-daemon.tgz
        docker image save localhost:5000/chaos-mesh/chaos-mesh:latest > ./output/saved-images/chaos-mesh.tgz
        docker image save localhost:5000/pingcap/e2e-helper:latest > ./output/saved-images/e2e-helper.tgz
    - name: upload saved images
      uses: actions/upload-artifact@v2
      with:
        name: saved-images
        path: ./output/saved-images
        retention-days: 7
  build-e2e-binary:
    runs-on: ubuntu-latest
    steps:
    - name: checkout codes
      uses: actions/checkout@v2
    - name: build e2e binary
      run: |
        make e2e-build
    - name: upload e2e binary
      uses: actions/upload-artifact@v2
      with:
        name: e2e-binary
        path: ./e2e-test/image/e2e/bin
        retention-days: 7
  e2e-all-tests:
    needs:
    - build-image
    - build-e2e-binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - v1.20.7
          - v1.21.1
        focus:
          - Basic
    steps:
    - name: checkout codes
      uses: actions/checkout@v2
    - name: download saved images
      uses: actions/download-artifact@v2
      with:
        name: saved-images
        path: ./output/saved-images
    - name: restore e2e images
      run: |
        docker load -i ./output/saved-images/chaos-dashboard.tgz
        docker load -i ./output/saved-images/chaos-daemon.tgz
        docker load -i ./output/saved-images/chaos-mesh.tgz
        docker load -i ./output/saved-images/e2e-helper.tgz
    - name: download e2e binary
      uses: actions/download-artifact@v2
      with:
        name: e2e-binary
        path: ./output/e2e-binary
    - name: move e2e binary
      run: |
        mkdir -p ./e2e-test/image/e2e/bin
        mv ./output/e2e-binary/ginkgo ./e2e-test/image/e2e/bin/ginkgo
        mv ./output/e2e-binary/e2e.test ./e2e-test/image/e2e/bin/e2e.test
        chmod +x ./e2e-test/image/e2e/bin/ginkgo
        chmod +x ./e2e-test/image/e2e/bin/e2e.test
    - name: Setup minikube
      uses: manusa/actions-setup-minikube@v2.4.3
      with:
        driver: docker
        minikube version: v1.24.0
        kubernetes version: ${{ matrix.kubernetes-version }}
        start args: --cni flannel
    - name: load image into minikube
      run: |
        minikube image load localhost:5000/chaos-mesh/chaos-dashboard:latest
        minikube image load localhost:5000/chaos-mesh/chaos-daemon:latest
        minikube image load localhost:5000/chaos-mesh/chaos-mesh:latest
        minikube image load localhost:5000/pingcap/e2e-helper:latest
    - name: Setup Helm
      uses: azure/setup-helm@v1
    - name: Install Chaos Mesh
      run: |
        helm upgrade --wait --install --create-namespace chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set images.registry=localhost:5000 --set dnsServer.create=true --set dashboard.create=true;
    - name: e2e tests
      env:
        FOCUS: ${{ matrix.focus }}
      run: |
        KUBECONFIG=~/.kube/config ./e2e-test/image/e2e/bin/ginkgo -p -focus="${FOCUS}" ./e2e-test/image/e2e/bin/e2e.test -- --e2e-image localhost:5000/pingcap/e2e-helper:latest
    - name: post run - extract profile info from kubernetes
      if: always()
      env:
        PROFILE_DIRECTORY: ./output/chaos-mesh-profile
      run: |
        mkdir -p $PROFILE_DIRECTORY/logs
        mkdir -p $PROFILE_DIRECTORY/manifests/pods
        mkdir -p $PROFILE_DIRECTORY/manifests/services
        for item in $(kubectl -n chaos-testing get pods --no-headers | awk '{print $1}'); do kubectl -n chaos-testing logs $item > $PROFILE_DIRECTORY/logs/$item.log; done;
        for item in $(kubectl -n chaos-testing get pods --no-headers | awk '{print $1}'); do kubectl -n chaos-testing get pod $item -oyaml > $PROFILE_DIRECTORY/manifests/pods/pod-$item.yaml; done;
        for item in $(kubectl -n chaos-testing get services --no-headers | awk '{print $1}'); do kubectl -n chaos-testing get services $item -oyaml > $PROFILE_DIRECTORY/manifests/services/service-$item.yaml; done;
        for item in $(kubectl -n chaos-testing get endpoints --no-headers | awk '{print $1}'); do kubectl -n chaos-testing get endpoints $item -oyaml > $PROFILE_DIRECTORY/manifests/services/endpoint-$item.yaml; done;
    - name: post run - upload Chaos Mesh profile info
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: profiling-${{ matrix.focus }}-k8s-${{ matrix.kubernetes-version }}
        path: ./output/chaos-mesh-profile
        retention-days: 7
