name: E2E test matrix

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  build image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: build e2e images
      run: |
        make image e2e-image
    - name: save docker images
      run: |
        mkdir -p ./output/saved-images
        docker image save localhost:5000/chaos-mesh/chaos-dashboard:latest > ./output/saved-images/chaos-dashboard.tgz
        docker image save localhost:5000/chaos-mesh/chaos-daemon:latest > ./output/saved-images/chaos-daemon.tgz
        docker image save localhost:5000/chaos-mesh/chaos-mesh:latest > ./output/saved-images/chaos-mesh.tgz
        docker image save localhost:5000/pingcap/e2e-helper > ./output/saved-images/e2e-helper.tgz
    - name: restore e2e images as artifact
      uses: actions/upload-artifact@v2
      with:
        name: saved-images
        path: ./output/saved-images

  e2e-all-tests:
    needs: build-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - v1.20.7
          - v1.21.1
          - v1.12.10
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: saved-images
        path: ./output/saved-images
    - name: restore e2e images
      run: |
        docker load ./output/saved-images/chaos-dashboard.tgz
        docker load ./output/saved-images/chaos-daemon.tgz
        docker load ./output/saved-images/chaos-mesh.tgz
        docker load ./output/saved-images/e2e-helper.tgz
    - name: Setup minikube
      uses: manusa/actions-setup-minikube@v2
      with:
        minikube version: v1.23.0
        kubernetes version: ${{ matrix.kubernetes-version }}
    - name: Setup Helm
      uses: azure/setup-helm@v1
    - name: Install Chaos Mesh
      run: |
        make docker-push-dns-server install
    - name: e2e tests
      run: |
        KUBECONFIG=~/.kube/config GINKGO_FLAGS=-p make e2e
