# This workflow would make sure that there are some changes on CHANGELOG.md or
# the label "no-need-update-changelog" is tagged on the PR.

name: "Must Update CHANGELOG"
on:
  pull_request:
    branches:
      - master
      - release-*
jobs:
  must-update-changelog:
    name: "Must Update CHANGELOG"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Skip if label exists"
        id: "skip-if-label-exists"
        env:
          LABEL_EXISTS: ${{ contains(github.event.pull_request.labels.*.name, 'no-need-update-changelog') }}
        run: |
          if [ "${LABEL_EXISTS}" = "true" ] ; then
            echo "no-need-update-changelog exists, skipping this check"
            exit 0
          fi
      - name: "Collect changes"
        id: "collect-changes"
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'no-need-update-changelog') }}
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changelog:
            - CHANGELOG.md
      - name: "Make sure CHANGELOG.md is updated"
        id: "check-changelog"
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'no-need-update-changelog') }}
        env: 
          CHANGELOG_UPDATED: ${{ steps.collect-changes.outputs.changelog }}
        run: |
          if [ "${CHANGELOG_UPDATED}" = "true" ] ; then
            echo "CHANGELOG.md is updated"
          else
            echo "CHANGELOG.md is not updated"
            exit 1
          fi
